import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#1c2024",
    color: "#fff",
  },
  header: {
    backgroundColor: "#b18461",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 15,
    margin: 15,
    marginTop: 40,
    borderRadius: 15,
    justifyContent: "center",
  },
  textHeader: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "bold",
    paddingVertical: 10,
  },
  containerForm: {
    flex: 5,
    paddingHorizontal: 25,
    alignContent: "center",
    justifyContent: "center",
  },
  containerInput: {
    paddingHorizontal: "20",
    paddingTop: "5",
    marginVertical: "10",
    justifyContent: "center",
    backgroundColor: "#FFFFF0",
    borderCurve: 100,
    borderRadius: 10,
  },
  textInput: {
    fontSize: 17,
    fontWeight: "bold",
    color: "#111",
    paddingBottom: 5,
    paddingTop: 15,
  },
  inputName: {
    backgroundColor: "#ccc",
    borderRadius: 10,
    padding: 10,
    marginBottom: 20,
    fontSize: 16,
    color: "#111",
    fontWeight: "bold",
  },
  inputServices: {
    backgroundColor: "#ccc",
    borderRadius: 10,
    padding: 10,
    marginBottom: 20,
    fontSize: 16,
    color: "#111",
    fontWeight: "bold",
    height: 100,
    textAlignVertical: "top",
  },
  inputSentence: {
    backgroundColor: "#ccc",
    borderRadius: 10,
    marginBottom: 20,
    fontSize: 16,
    color: "#111",
    fontWeight: "bold",
  },
  buttonUpload: {
    backgroundColor: "#ccc",
    borderRadius: 10,
    padding: 10,
    marginBottom: 20,
    fontSize: 16,
    color: "#111",
    fontWeight: "bold",
    height: 100,
    textAlignVertical: "top",
    alignItems: "center",
    justifyContent: "center",
  },
  containerImage: {
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  imageUpload: {
    width: 150,
    height: 150,
    resizeMode: "cover",
  },
  inputFone: {
    backgroundColor: "#ccc",
    borderRadius: 10,
    padding: 10,
    marginBottom: 20,
    fontSize: 16,
    color: "#111",
    fontWeight: "bold",
  },
  inputEmail: {
    backgroundColor: "#ccc",
    borderRadius: 10,
    padding: 10,
    marginBottom: 20,
    fontSize: 16,
    color: "#111",
    fontWeight: "bold",
  },
  picker: {
    borderRadius: 10,
    border: "none",
    backgroundColor: "#ccc",
    marginBottom: 20,
  },
  submitForm: {
    fontSize: 35,
    backgroundColor: "#b18461",
    borderCurve: 100,
    paddingVertical: 15,
    marginVertical: 20,
    marginBottom: 50,
    borderRadius: 50,
    width: 200,
    alignItems: "center",
    alignSelf: "center",
  },
  textSubmitForm: {
    fontSize: 25,
    fontWeight: 700,
    color: "#E4E4E4",
  },
  error: {
    color: "#ff0000",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
  },
});
export default styles;
